package com.pangio.company

public enum Country {

    ALGERIA, ANGOLA, BOTSWANA, BURKINA_FASO, BURUNDI, CAMEROON, REPUBLIC_CHAD, CONGO, RO, EGYPT, ERITREA, ETHIOPIA, GAMBIA, GHANA, GUINEA_BISSAU, IVORY_COAST, KENYA, LESOTHO, LIBERIA, LIBYA, MADAGASCAR, MALAWI, MAURITANIA, MOROCCO, MOZAMBIQUE, NAMIBIA, NIGER, NIGERIA, RWANDA, SENEGAL, SIERRA, LEONE, SOMALIA, SOUTH_AFRICA, SUDAN, SURINAME, SWAZILAND, TANZANIA, TOGO, TUNISIA, WESTERN_SAHARA, YEMEN, ZAMBIA, ZIMBABWE,

    AFGHANISTAN, ARMENIA, AZERBAIJAN, BAHRAIN, BANGLADESH, BHUTAN, CAMBODIA, CHINA, HONG_KONG, EAST_TIMOR, GEORGIA, INDIA, IRAN, IRAQ, JAPAN, JORDAN, KAZAKHSTAN, KUWAIT, KYRGYZSTAN, MALAYSIA, MONGOLIA, MYANMAR, NEPAL, NORTH_KOREA, OMAN, PAKISTAN, PALESTINIAN_TERRITORIES, PAPUA, NEW_GUINEA, QATAR, SAUDI, ARABIA, SINGAPORE, SOUTH_KOREA, SRI_LANKA, SYRIA, TAIWAN, TAJIKISTAN, THAILAND, TURKEY, TURKMENISTAN, UNITED_RAB, EMIRATES, UZBEKISTAN, VIETNAM,

    ALBANIA, AUSTRIA, BELARUS, BELGIUM, BOSNIA_AND_HERZEGOVINA, BULGARIA, CROATIA, CYPRUS, CZECH_REPUBLIC, DENMARK, ESTONIA, FINLAND, FRANCE, GERMANY, GREECE, HUNGARY, ICELAND, IRELAND, ITALY, LATVIA, LITHUANIA, MACEDONIA, MOLDOVA, MONTENEGRO, NETHERLANDS, POLAND, PORTUGAL, ROMANIA, RUSSIA, SERBIA, SLOVAKIA, SLOVENIA, SPAIN, SWEDEN, SWITZERLAND, UKRAINE, UNITED_KINGDOM,

    BAHAMAS, BELIZE, CANADA, COSTA, RICA, CUBA, DOMINICAN_REPUBLIC, EL_SALVADOR, GREENLAND, GUATEMALA, HAITI, HONDURAS, JAMAICA, MEXICO, NICARAGUA, PANAMA, TRINIDAD_AND_TOBAGO, UNITED_STATES, PUERTO_RICO,

    AUSTRALIA, FIJI, NEW_ZEALAND,

    ARGENTINA, BOLIVIA, BRAZIL, CHILE, COLOMBIA, ECUADOR, GUYANA, PARAGUAY, PERU, URUGUAY, VENEZUELA;

    public static Country getRandom() {
        return values()[(int) (Math.random() * values().size())];
    }
}